# docker-compose.yml
services:
  app:
    build: .
    command: php artisan serve --host=0.0.0.0 --port=9000
    volumes:
      - ./:/app
    ports:
      - "8000:9000"
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
