version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Use the same CMD as in Dockerfile (caches at runtime)
    environment:
      - PORT=9000
    ports:
      - "8000:9000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
